"""Add FK seller_id  and relationship seller_info for Products table

Revision ID: 000ef7aaab14
Revises: 5c935fbad435
Create Date: 2023-07-04 00:28:46.850993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000ef7aaab14'
down_revision = '5c935fbad435'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('seller_id', sa.Integer(), nullable=False))
    op.drop_constraint('products_owner_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['seller_id'], ['id'], ondelete='CASCADE')
    op.drop_column('products', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_owner_id_fkey', 'products', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('products', 'seller_id')
    # ### end Alembic commands ###
