"""edit role rules for  user table

Revision ID: 29cc86ce556e
Revises: c506d47f5b73
Create Date: 2023-07-03 18:14:41.241654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29cc86ce556e'
down_revision = 'c506d47f5b73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
