"""add order_qty column for  orders table

Revision ID: 2b12ecf90276
Revises: 33ebce280a23
Create Date: 2023-07-04 15:03:09.751811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b12ecf90276'
down_revision = '33ebce280a23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_qty', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_qty')
    # ### end Alembic commands ###
