"""edit role rules for  user table 8

Revision ID: 2b8c6e5bf759
Revises: b211ddeb624b
Create Date: 2023-07-03 18:36:13.341861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b8c6e5bf759'
down_revision = 'b211ddeb624b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
