"""add edit column post_id -> product_id

Revision ID: 3132124a4208
Revises: afc61dbed21b
Create Date: 2023-07-05 01:11:44.160250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3132124a4208'
down_revision = 'afc61dbed21b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_id', sa.Integer(), nullable=True))
    op.drop_constraint('cart_post_id_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'orders', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cart', 'post_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_post_id_fkey', 'cart', 'orders', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cart', 'product_id')
    # ### end Alembic commands ###
