"""edit role rules for  user table 2

Revision ID: 4029591b8cf6
Revises: 29cc86ce556e
Create Date: 2023-07-03 18:16:31.186168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4029591b8cf6'
down_revision = '29cc86ce556e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
