"""edit role rules for  user table 7

Revision ID: 4e58a207c713
Revises: 791fee7d0b43
Create Date: 2023-07-03 18:32:10.549644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e58a207c713'
down_revision = '791fee7d0b43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
