"""fix fk product_id of carts table

Revision ID: 54ea8a9bf0c0
Revises: 3132124a4208
Create Date: 2023-07-05 01:14:10.124513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ea8a9bf0c0'
down_revision = '3132124a4208'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_product_id_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_product_id_fkey', 'cart', 'orders', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
