"""add relationship for carts table

Revision ID: 568fa09f5c99
Revises: 54ea8a9bf0c0
Create Date: 2023-07-05 01:20:07.795815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568fa09f5c99'
down_revision = '54ea8a9bf0c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
