"""add product relationship for  orders table

Revision ID: 67c32f46383d
Revises: 2b12ecf90276
Create Date: 2023-07-04 15:24:17.850665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c32f46383d'
down_revision = '2b12ecf90276'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
