"""edit role rules for  user table 6

Revision ID: 791fee7d0b43
Revises: f30fcb3c471f
Create Date: 2023-07-03 18:30:05.202158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791fee7d0b43'
down_revision = 'f30fcb3c471f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
