"""empty message

Revision ID: 798265c8e37f
Revises: d3bdc93b817b
Create Date: 2023-07-02 02:27:05.724401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798265c8e37f'
down_revision = 'd3bdc93b817b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image')
    # ### end Alembic commands ###
