"""created_at column to cart table

Revision ID: 825b54c5bdad
Revises: 568fa09f5c99
Create Date: 2023-07-05 02:36:47.004664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825b54c5bdad'
down_revision = '568fa09f5c99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'created_at')
    # ### end Alembic commands ###
