"""Column isSeller -> is_seller role column final

Revision ID: 9563e83bf2ef
Revises: f0ddb62b4905
Create Date: 2023-07-03 23:51:08.559187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9563e83bf2ef'
down_revision = 'f0ddb62b4905'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_Seller', sa.Boolean(), server_default='FALSE', nullable=True))
    op.drop_column('users', 'isSeller')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isSeller', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_Seller')
    # ### end Alembic commands ###
