"""add edit column post_id -> product_id

Revision ID: afc61dbed21b
Revises: 4b08e4ee538c
Create Date: 2023-07-05 01:11:20.565912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc61dbed21b'
down_revision = '4b08e4ee538c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
