"""edit role rules for  user table 7

Revision ID: b211ddeb624b
Revises: 4e58a207c713
Create Date: 2023-07-03 18:35:59.787702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b211ddeb624b'
down_revision = '4e58a207c713'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
