"""edit role rules for  user table 7

Revision ID: d2ebf4335bfa
Revises: 2b8c6e5bf759
Create Date: 2023-07-03 18:52:14.198509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ebf4335bfa'
down_revision = '2b8c6e5bf759'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
