"""edit role rules for  user table 3

Revision ID: d46848cf5402
Revises: 4029591b8cf6
Create Date: 2023-07-03 18:19:09.805046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46848cf5402'
down_revision = '4029591b8cf6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
