"""re-add role column 2

Revision ID: eda514ba6f97
Revises: d9c29ac4e6af
Create Date: 2023-07-03 19:06:01.948962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda514ba6f97'
down_revision = 'd9c29ac4e6af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
