"""re-add role column 3

Revision ID: f0ddb62b4905
Revises: fbe4be2f8b14
Create Date: 2023-07-03 19:08:34.897958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ddb62b4905'
down_revision = 'fbe4be2f8b14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isSeller', sa.Boolean(), server_default='FALSE', nullable=True))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'isSeller')
    # ### end Alembic commands ###
