"""edit role rules for  user table 5

Revision ID: f30fcb3c471f
Revises: cf14183c1b49
Create Date: 2023-07-03 18:25:27.502733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f30fcb3c471f'
down_revision = 'cf14183c1b49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.alter_column('User', 'role', default="213123", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
