"""re-add role column 3

Revision ID: fbe4be2f8b14
Revises: eda514ba6f97
Create Date: 2023-07-03 19:07:00.389986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe4be2f8b14'
down_revision = 'eda514ba6f97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
